version: "3.9"

services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        USERNAME: ${USERNAME-vscode}
        USER_UID: ${USER_UID-1000}
        USER_GID: ${USER_GID-1000}
        TIME_ZONE: ${TIME_ZONE-UTC}
        LOCALE: ${LOCALE-C}
    ports:
      - "${IP_ADDRESS_SETTING}80:80"
      - "${IP_ADDRESS_SETTING}443:443"
    cap_add:
      - NET_ADMIN
    tty: true
    volumes:
      - ../:/var/www
      - ./docker/workspace/config/php.ini:/usr/local/etc/php/conf.d/99-php.ini
    working_dir: /var/www